modLoader="javafml"
loaderVersion="[47,)"
issueTrackerURL = "https://github.com/TheGridExpert/VampiresDelight/issues"
license="MIT"
[[mods]]
modId="vampiresdelight"
version="0.0.1.3"
displayName="Vampire's Delight"
displayURL = "https://github.com/TheGridExpert/VampiresDelight"
logoFile="logo.png"
logoBlur=false
itemIcon = "vampiresdelight:garlic_crate"
configBackground = "vampirism:textures/block/dark_stone_bricks.png"
credits="Cheaterpaul, Maxanier, Vectorwing"
authors="GridExpert"
description='''
Makes Vampirism and Farmer's Delight more compatible
'''
[[dependencies.vampiresdelight]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"
[[dependencies.vampiresdelight]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,)"
ordering="NONE"
side="BOTH"
[[dependencies.vampiresdelight]]
modId="vampirism"
mandatory=true
versionRange="[1.10.6,)"
ordering="NONE"
side="BOTH"
[[dependencies.vampiresdelight]]
modId="farmersdelight"
mandatory=true
versionRange="[1.20.1-1.2.3,)"
ordering="NONE"
side="BOTH"