
[common_server]
	#Only considered if terrablender installed. Heigher values increase Werewolf region weight (likelyhood to appear)
	#Range: 1 ~ 1000
	werewolfHeavenWeightTerrablender = 2
	#Disable werewolf heaven generation
	disableWerewolfHeaven = false
	#Weight of silver ore spawning
	#Range: 0 ~ 256
	silverOreWeight = 30

